#!/usr/bin/env node
require('shelljs/global');

var from;
var to;

cd('./.sublime');
ls('*.sublime-*').forEach(function (file) {
  switch(file) {
    case 'Package Control.sublime-settings':
      from = pwd() + '/' + file;
      pushd('-n', '~/Library/Application Support/Sublime Text 3/Packages/User');
      echo(dirs(-1));
      //ln('-s', file, '~/Library/Application Support/Sublime Text 3/Packages/User/' + file);
      break;
    case 'Default (OSX).sublime-keymap':
      //echo(file);
      break;
    case 'Preferences.sublime-settings':
      //echo(file);
      break;

    // ln('-sf', 'file', 'existing');
  }
});
